# Read the Docs configuration file for Sphinx projects
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12.3"

sphinx:
  configuration: docs/conf.py
  builder: "dirhtml"
  fail_on_warning: true

# Fix the indentation for these sections
formats:
  - pdf

python:
  install:
    - requirements: docs/requirements.txt