name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12.3]
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      DJANGO_SETTINGS_MODULE: oc_lettings_site.settings

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: flake8

      - name: Run tests
        run: pytest

      - name: Collect static files
        run: python manage.py collectstatic --noinput

      - name: Build Docker image
        run: docker build \
          --build-arg SECRET_KEY=${{ secrets.SECRET_KEY }} \
          --build-arg SENTRY_DSN=${{ secrets.SENTRY_DSN }} \
          -t oc-lettings-site .
